[theme]
primaryColor="#0068c9"
backgroundColor="#F0F2F6"
secondaryBackgroundColor="#FFFFFF"
textColor="#0a1435"
font="sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[custom]
# Configurações da aplicação
google_api_key = ""
supabase_url = ""
supabase_key = ""

[browser]
gatherUsageStats = false